---
title: "Google Drive Links"
description: |
  A slightly more organized way to get to various docs saved in Google Drive
favicon: docs/images/favicon.ico
output: 
  distill::distill_article:
    self_contained: true
    toc: true
    toc_depth: 4
    toc_float: true
    css: static/toc-styles.css
---

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.align = 'center')

library(fontawesome)
```

Most (all?) of these live in various folders within the [**LLHARP Master**](https://drive.google.com/drive/u/0/folders/0BxY-_FjiYpOqRVNYbi1iTFBPSkk?resourcekey=0-vquRfPYWfEjmdNjWsjB7jQ){target='_blank'} Google Drive folder. 

[**Project Management**](https://docs.google.com/document/d/1ReMTYiU1ZlUmcYkOsV70ii5NW79abwt_II2aUSclZeE/edit#heading=h.arpv8eucrye4){target='_blank'}: Google Doc with outline of all project steps/components and who is in charge of what. *This is somewhat outdated as of January 2023, and is meant to be replaced by this hub!* 

### Metadata

[**LLHARP Data Summary**](https://docs.google.com/spreadsheets/d/1S0e3T8GijoM0NTLCLjKV_9d3C9_YnHNqZhkV0BNJkzg/edit#gid=0){target='_blank'}: Metadata for every trip including hardware and software versions, data size and records of data uploads, and notes on issues or concerns. This document does contain vessel names and trip dates so access is restricted to those it has been shared with through GDrive. 

[**Longline HARP Deployments**](https://docs.google.com/spreadsheets/d/18i4czz6so-GHgFrCRncpLNZxTErdu4yFvi-Z-VwTEdM/edit#gid=1521628320):
Record of trip numbers, vessels, and captain/owner/observer contact information. This contains vessel names, trip dates, and personal info so it is restricted to only being shared within our group. 

[**Acoustic Server Data Organization**](https://docs.google.com/spreadsheets/d/12dkFpM7FA4qUG-K3MNQCJFebb_e-9eTtFJ_p4G_hbAs/edit#gid=337699346){target='_blank'}: Detailed list of server locations for all acoustic data, including LLHARP data. This document is restricted to only being shared within our group. 


### Vessel recruitment

[**Confirmed Vessel List**](https://docs.google.com/spreadsheets/d/1i1eNu9zobr14yhx8RAXGHmk0pTh6a7s-/edit?rtpof=true#gid=1725502758){target="_blank"}: This contains vessel names and contact information for owners and captains that have volunteered or have previously taken gear. This contains personal info for the vessels and so has restricted access to only those it has been shared with. 

### Hardware

[LLHARP Tracker 2.0](https://docs.google.com/spreadsheets/d/1yFXe0Q-HPl6Xwyz5cbyfeEJlM1wSGe0aaEqKY4Ttkbg/edit#gid=0){target="_blank"}: Spreadsheet to keep track of gear status (hydrophones, cases, etc). This doc is shared with SIO. 

[TDR_CRP_Usage](https://docs.google.com/spreadsheets/d/13qwMA_cUG8n1i4OXqbWIJ0Pu58Ho1kx-tPw6Fci7jZ0/edit#gid=838073579){target="_blank"}: Spreadsheet to track status of TDRs and record of deployments; this doc is also used for DASBRs.

[Zoom Recorder Tracker](https://docs.google.com/spreadsheets/d/1mHXUQGTg27jBXjwE2POs3XdcJykounqL/edit#gid=1787322236){target='_blank'}: Spreadsheet to track status/location of Zoom recorders. 

[Longline HARP User Manual](https://drive.google.com/drive/u/0/folders/1khqpzKseolLlXRJ8Yf2aep9uQOuhWYdD){target='_blank'} *April 2021*

[Blank metadata check sheet](https://drive.google.com/drive/u/0/folders/1khqpzKseolLlXRJ8Yf2aep9uQOuhWYdD){target='_blank'}

[**Instructions for Deployment Set-Up and Recovery**](https://docs.google.com/document/d/1EksOga_cyEPW9utMeLDw1ErR-eTIEvCzoO8l2v_Onrg/edit#heading=h.zdtttamxmx79){target='_blank'}: This is a very thorough protocol document that can be eventually converted to Rmd. Last updated *13 August 2021*

*old protocol* [**LLHARP Part I - Setup, Deploy, Recover.doc**](https://docs.google.com/document/d/0BxY-_FjiYpOqN3lmUHJyZ0JIbzQ/edit?rtpof=true&resourcekey=0-0lrFjbKIafQhui1ttAzwag){target='_blank'}: Older protocol, last updated *17 March 2017*


### Data processing

*old protocol* [**LLHARP Part II - Data Processing**](https://docs.google.com/document/d/1po1G2isgSCfYWc1dj8XphotPeZuOZ22ugL5wsc9o3JY/edit){target='_blank'} Google Doc *9 August 2022*

### Analysis

All Pamguard preferences files, etc have been moved to GitHub, to the private [llamp](https://github.com/sfregosi/llamp){target='_blank'} repository. Create an [issue](https://github.com/sfregosi/llamp/issues/new){target='_blank'} to request access. 

### Reporting

[**HARP Noise of Interest Captain Feedback Log**](https://docs.google.com/spreadsheets/d/1bGmRu3xXq9RJQZvMprcRzZe-27sX6kv-tclNldokcy8/edit#gid=0){target='_blank'}: Some older notes on ideas of what the noise might be, collected by Colby at Protected Species trainings. 




## Last Updated {.appendix}

`r fa(name = "calendar-check")` `r format(Sys.Date(), "%d %B %Y")`


