on:
  push:

name: update-github-pages

jobs:
  update-website:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install packages
        run: Rscript -e 'install.packages(c("rmarkdown", "distill", "postcards", "knitr", "fontawesome", "xaringanExtra", "htmltools"))'

      - name: Build site
        run: Rscript -e 'rmarkdown::render_site(encoding = 'UTF-8')'

      - name: Set up Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
      - name: Commit all changes
        run: |
          git add -A && git commit -m ':rocket: Build site' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
